# this ClusterIP service is for the connetion between the Ingress controller and the api
apiVersion: v1
kind: Service
metadata:
  name: api-clusterip-service
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - port: 3000
      targetPort: 3000