clusterName: "testELK"
replicas: 1
minimumMasterNodes: 1
createCert: true
secret:
  enabled: true
  password: ""
image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "8.5.1"
resources:
  requests:
    cpu: "200m"
    memory: "500Mi"
  limits:
    cpu: "300m"
    memory: "1Gi"
ingress: 
  enabled: false  # enable it only for external access to the cluster
  hosts:
    - host: elastic.babak.orf
      paths:
        - path: /

# helm install elasticsearch -f elasticsearch-values.yaml stable/elasticsearch
