apiVersion: v1
kind: Pod
metadata:
  name: myapp-with-init
  labels:
    name: myapp-with-init
spec:
  # First we run the init container 1, then init container2, and at last the main app container. This is very useful for cases when you have to wait for another server to come up before running your app.
  containers:
    - name: myapp-with-init
      image: busybox
      resources:
        limits:
          memory: "64Mi"
          cpu: "50m"
      ports:
        - containerPort: 80

  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command:
        [
          "sh",
          "-c",
          "until nslookup mysvc.namespace.svc.cluster.local; do echo waiting for myservice; sleep 2; done",
        ]

    - name: init-mydb
      image: busybox:1.28
      command:
        [
          "sh",
          "-c",
          "until nslookup mydb.namespace.svc.cluster.local; do echo waiting for mydb; sleep 2; done",
        ]
