apiVersion: v1
kind: Pod
metadata:
  labels:
    name: liveness
  name: liveness-http
spec:
  containers:
    - name: liveness
      image: k8s.gcr.io/liveness
      args:
        - /bin/bash
        - -c
        - touch /tmp/healthy; sleep 15; rm -rf /tmp/healthy; sleep 3600
      livenessProbe:
        exec:
          command: # cat /tmp/healthy
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
      resources: {}
