apiVersion: v1
kind: Pod
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  containers:
    - name: goproxy
      image: k8s.gcr.io/goproxy:0.1
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
      ports:
        - containerPort: 8080

      # to check if container is ready to accept traffic
      # wait at first 5 seconds, then 10s each round until it is ready to accept traffic
      # readiness probe will run DURING THE WHOLE POD LIFECYCLE
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 5

      # to check if the code is running or not
      # at first delay 15 seconds, then check every 20 until we see if the container is running the code
      # if failure is consistent, will cause the pod to restart
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
        failureThreshold: 3

      # the first probe, this is when application starts to run
      # try 3 times and after each time wait 10 seconds, if then api is unavailable, restart the pod
      startupProbe:
        httpGet:
          path: /healthz
          port: 80
        failureThreshold: 3
        periodSeconds: 10
