apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-fetcher
  namespace: mddz
spec:
  selector:
    matchLabels:
      app: configuration-fetcher
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: configuration-fetcher
    spec:
      volumes:
        - name: configuration-fetcher-logs
          persistentVolumeClaim:
            claimName: configuration-fetcher-logs-claim
      securityContext:
        runAsUser: 10000
        runAsGroup: 10001
      imagePullSecrets:
        - name: my-reg-key
      containers:
      - name: configuration-fetcher
        image: registry.***.****.com/mddz/configuration-fetcher:1.0.0-SNAPSHOT
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8081
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "remote,dev"

        - name: mddz_EUREKA_PEER1_HOST
          value: service-registry-service-1

        - name: mddz_EUREKA_PEER2_HOST
          value: service-registry-service-2

        - name: mddz_EUREKA_PEER3_HOST
          value: service-registry-service-3

        - name: mddz_EUREKA_PORT
          value: "8761"

        - name: mddz_EUREKA_USER_NAME
          value: "****"

        - name: MSDDR_EUREKA_USER_PASSWORD
          valueFrom:
           secretKeyRef:
            name: eureka-pass-secret
            key: eureka-pass

        resources:
          requests:
            cpu: 50m
            memory: 150Mi
          limits:
            cpu: 160m
            memory: 350Mi
        volumeMounts:
          - name: configuration-fetcher-logs
            mountPath: /home/mddz/logs/configuration-fetcher/${INSTANCE}        
---
apiVersion: v1
kind: Service
metadata:
  name: configuration-fetcher-service
  namespace: mddz
spec:
  type: ClusterIP
  selector:
    app: configuration-fetcher
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
