apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: mddz
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.5.1
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: logstash-conf
            mountPath: /usr/share/logstash/pipeline/logstash.conf
            subPath: logstash.conf
          - name: logstash-yml
            mountPath: /usr/share/logstash/config/logstash.yml
            subPath: logstash.yml
        ports:
        - containerPort: 5044
        imagePullPolicy: IfNotPresent
        env:
        - name: ELASTICSEARCH_HOST
          value: "***.**.***.com"
        - name: ENVIRONMENT
          value: "dev"

        resources:
          requests:
            cpu: 80m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 250Mi

      volumes:
        - name: logstash-conf
          configMap: 
            name: logstash-conf
        - name: logstash-yml
          configMap: 
            name: logstash-yml
---

apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: mddz
spec:
  type: ClusterIP
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
