apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-auto-scaler
  namespace: mddz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # can be also setup for any microservice if needed
    name: config-server
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
  # Min-Max
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
