version: '3'
services:

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  api:
    build: 
      dockerfile: Dockerfile
      context: './server'
    volumes:
    # do not copy contents of the /app/node_modules folder
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: './client'
    volumes:
      - /app/node_modules
      - ./client:/app

  nginx:
  # nginx depends on client and server, because it should run AFTER them
    depends_on:
      - api
      - client
    restart: always
    build: 
      dockerfile: Dockerfile
      context: './nginx'
    ports:
      - "3050:80"
      
