{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "springboot-microservice.namespace" . }}
  labels:
    kubernetes.io/metadata.name: {{ include "springboot-microservice.namespace" . }}
{{- with .Values.namespace.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
