{{- if .Values.secrets.create }}
{{- range $name, $secret := .Values.secrets.items }}
{{- if ne $secret.enabled false }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ include "springboot-microservice.namespace" $ }}
  labels:
{{ include "springboot-microservice.labels" $ | indent 4 }}
type: {{ default "Opaque" $secret.type }}
{{- with $secret.stringData }}
stringData:
{{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- with $secret.data }}
data:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
