{{- if .Values.serviceAccounts.create }}
{{- range .Values.serviceAccounts.names }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  namespace: {{ include "springboot-microservice.namespace" $ }}
  labels:
{{ include "springboot-microservice.labels" $ | indent 4 }}
automountServiceAccountToken: {{ $.Values.serviceAccounts.automountServiceAccountToken }}
{{- end }}
{{- end }}
