appName: schemaregistry
namespace: dbekfk-schemareg
kafka-password: 4534534534534=
appImageFirst: ************.net/prod-infra/solsson/kafka-prometheus-jmx-exporter:latest
appImageSecond: *************.net/prod-infra/confluentinc/cp-schema-registry:7.4.0
containerEnvVars:
- name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
  value: '"SASL_PLAINTEXT://10.254.15.221:9092,SASL_PLAINTEXT://10.254.0.220:9092,SASL_PLAINTEXT://10.254.15.224:9092"'
- name: SCHEMA_REGISTRY_LISTENERS
  value: '"http://0.0.0.0:8081"'
- name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
  value: '"SASL_PLAINTEXT"'
- name: SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM
  value: '"SCRAM-SHA-256"'
- name: SCHEMA_REGISTRY_DEBUG
  value: '"true"'
- name: SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL
  value: INFO
- name: SCHEMA_REGISTRY_INIT_TIMEOUT_MS
  value: '"800000"'
- name: SCHEMA_REGISTRY_JMX_PORT
  value: '"8082"'
- name: SCHEMA_REGISTRY_JMX_ENABLED
  value: '"true"'
- name: SCHEMA_REGISTRY_JMX_OPTS
  value: '"-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=8082"'

notalpha: false
enabled: false

secondVolume:
 volumeName: jmx-config
 volumePath: /etc/jmx-schema-registry

serviceType: NodePort

# virtualService:
#   name: ap-schemaregistry-app
#   gateway: asmgwy-net/schemaregistry-gwy
#   host: *******.net
#   destHost: schemaregistry-nodeport
#   destHostPort: 8081

# ingress:
#   class: gce-internal
#   StaticIpName: ip-schemareg-app-usea1-al-01
#   preSharedCert: us-prd-rdsdfc-net
#   allowHttp: false
#   serviceName: schemaregistry-nodeport
#   servicePort: 8081