apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dep
spec:
  replicas: 3

  # this section is for how updating the pods should happen
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # how many new pods to create when all the old pods already exist
      maxSurge: 1
      # how many of the old pods are allowed to be unavailable at once
      maxUnavailable: 1

  selector:
    matchLabels:
      app: hello-dep
  template:
    metadata:
      labels:
        app: hello-dep
    spec:
      containers:
        - name: hello-dep
          image: k8sacademy/hello-app:1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
