apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-nodeport
  namespace: {{ .Values.namespace }}
  {{- if .Values.enabled }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  {{- end }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - name: {{ .Values.appName }}
    port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.serviceType }}
