{{- if .Values.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - {{ .Values.virtualService.gateway }}
  hosts:
    - {{ .Values.virtualService.host }}
  http:
    - route:
        - destination:
            host: {{ .Values.virtualService.destHost }}
            port:
              number: {{ .Values.virtualService.destHostPort }}
{{- end }}
