---
# if you apply this file via "kubectl apply -f" command, it will create autoscaling hpa on the desired deployment

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
spec:
  # max number of pods allowed for deployment
  maxReplicas: 4
  # min number of pods per deployment
  minReplicas: 1
  # target cpu level at 45% on each pod, if the cpu utilization goes higher, increase the number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 45
  # which deployments this will be applied to
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  # which deployments this will be applied to
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  # target cpu level at 50% on each pod, if the cpu utilization goes higher, increase the number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eclipse # the HPA usaually have same name as the deployment its affecting
  namespace: xx1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eclipse
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
