---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: dev
rules:
  # Empty string means the core API group
  - apiGroups: [""]
    # K8s components like pods, deployments,...
    resources: ["pods"]
    # Allowed actions on the resource by this Role:
    verbs: ["list", "get", "create", "update", "delete"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update", "delete"]
    # Limit these verbs to specific ConfigMap names
    # resourceNames cannot restrict "create" because the object name may not exist yet
    resourceNames:
      - "blue"
      - "orange"

---
# RoleBinding connects a Role to Users and Groups

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser-developer-binding
  namespace: dev
# Subjects bound to the Role can be Users, Groups, or ServiceAccounts.
subjects:
  - kind: User
    name: dev-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role # this must be Role or ClusterRole
  name: developer
  apiGroup: rbac.authorization.k8s.io



---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: blue
rules:
  - apiGroups:
      - ""
    # Only allow operations on the Pod with this specific name
    resourceNames:
      - dark-blue-app
    resources:
      - pods
    verbs:
      - get
      - watch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create



---
# ClusterRoles are cluster-scoped and are not tied to a specific namespace

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-admin
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: michelle-binding
subjects:
  - kind: User
    name: michelle
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-admin



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-admin
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "watch", "list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: michelle-storage-admin
subjects:
  - kind: User
    name: michelle
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: storage-admin
  apiGroup: rbac.authorization.k8s.io



# Group Binding to ClusterRole (so all users within that group can access the Role)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secret-global
subjects:
  - kind: Group
    name: cluster-admins
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admins-role
  apiGroup: rbac.authorization.k8s.io


# User `smoke` should have `view` permissions (like the permissions of the default ClusterRole named `view`) in all Namespaces but not in kube-system =>
# you are allowed to bind a clusterRole to a namespace via RoleBinding process

# k get ns
# NAME                 STATUS   AGE
# applications         Active   12m
# default              Active   13d
# kube-node-lease      Active   13d

# k -n applications create rolebinding test-view --clusterrole=view --user=smoke
# k -n default create rolebinding smoke-view --clusterrole=view --user=smoke
# k -n kube-node-lease create rolebinding smoke-view --clusterrole=view --user=smoke



# create a new serviceAccount "gitops" in namespace "project-1", create role and rolebinding both named "gitops-role" and "gitops-rolebinding". allows the SA to create secrets and configmaps in the namespace

# k create serviceaccount gitops -n project-1
# k create role gitops-role -n project-1 --verb=create --resources=secret,configmaps
# k create rolebinding gitops-rolebinding -n project-1 --role=gitops-role --serviceaccount=gitops
# k auth can-i create secret -n project-1 --as system:serviceaccount:project-1:gitops



# Binding a Service account to a Role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: environment-validator
  namespace: webhook-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: webhook-system
  name: environment-validator-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: environment-validator-binding
  namespace: webhook-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: environment-validator-role
subjects:
  - kind: ServiceAccount
    name: environment-validator
    namespace: webhook-system