# If the file doesn't show on the second pod but it shows on the first, it has most likely been scheduled on a different node.
# check which nodes the pods are on
# k get po busybox -o wide
# k get po busybox2 -o wide
# If they are on different nodes, you won't see the file, because we used the hostPath volume type. If you need to access the same files in a multi-node cluster, you need a volume 
# type that is independent of a specific node. general solution could be to use NFS.


apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvolume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: normal
  # hostPath only works on ONE node (it gives address on HOST MACHINE)
  hostPath:
    path: /etc/foo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: normal
  resources:
    requests:
      storage: 4Gi
  accessModes:
  - ReadWriteMany

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
spec:
  volumes:
    - name: my-vol
      persistentVolumeClaim:
        claimName: mypvc
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh","-c","sleep 3600"]
      volumeMounts:
      - name: my-vol
        mountPath: /etc/foo

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
spec:
  volumes:
    - name: my-vol
      persistentVolumeClaim:
        claimName: mypvc
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh","-c","sleep 3600"]
      volumeMounts:
      - name: my-vol
        mountPath: /etc/foo