apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: {{ .Values.namespace.vault }}
  labels:
    {{- with .Values }}
      {{- include "ics-labels.labels" . | nindent 4 }}
    {{ end }}
data:
  address: {{ .Values.hashicorpVault.address }}
  SECRET_PREFIX: "dev"
  STATIC_SECRET_PREFIX: "default/dev"
  SECRET_VERSION: "1"
  SECRET_MOUNT_POINT: "secret"
  AUTH_K8S_BACKEND: kubernetes
  VAULT_INSTALLER_VAULT_ROLE: {{ .Values.hashicorpVault.accessRole }}