apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.service.namespace }}"
  labels:
    name: "{{ .Values.service.namespace }}"
    # Label related to istio
    spyder_mesh_id: svcs-mesh
    app.kubernetes.io/name: {{ .Values.service.namespace }}
    {{- with .Values }}
      {{- include "ics-labels.namespace" . | nindent 4 }}
    {{end}}