apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  namespace: "{{ .Values.service.namespace }}"
  labels:
    {{- with .Values }}
      {{- include "ics-labels.labels" . | nindent 4 }}
    {{end}}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: http-actuator
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: {{ .Values.service.name }}