# Pod Disruption Budget

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb-1
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: zookeeper


---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb-2
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: zookeeper
