apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-demo
spec:
  containers:
    # side car container
    - image: busybox
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "while true; do echo echo $(date -u) 'Hi I am from Sidecar container' >> /var/log/index.html; sleep 5;done",
        ]
      name: sidecar-container
      resources: {}
      volumeMounts:
        # both containers access a shared volume
        - name: var-logs
          mountPath: /var/log

    # main container, uses the data that comes from sidecar container and shows it
    - image: nginx
      name: main-container
      resources: {}
      ports:
        - containerPort: 80
      volumeMounts:
        # both containers access a shared volume
        - name: var-logs
          mountPath: /usr/share/nginx/html

  dnsPolicy: Default
  volumes:
    - name: var-logs
      emptyDir: {}
