apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secret-bearer-token
  namespace: monitoring
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: "2349-1110ie-core-vt-monitoring"
        objectType: "secretmanager"