# all the values in here can come from a values.yml file that contains them
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  # will use default if niether of the values here are filled
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    version: {{ .Values.image.tag }}
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.image.tag }}
        env: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "khaosdoctor/zaqar:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SENDGRID_APIKEY
              # if we don't give it the needed value, with abort the process and show the error message
              value: {{ required "You must set a valid Sendgrid API key" .Values.environment.SENDGRID_APIKEY | quote }}
            - name: DEFAULT_FROM_ADDRESS
              value: {{ required "You must set a default from address" .Values.environment.DEFAULT_FROM_ADDRESS | quote }}
            - name: DEFAULT_FROM_NAME
              value: {{ required "You must set a default from name" .Values.environment.DEFAULT_FROM_NAME | quote }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}


Comment: >
      how to inject variables into the helm from cmd
      helm upgrade --install --create-namespace myChart ./path/to/my/chart \
      --set image.tag=v1.0.0 \
      --set env=production \
      --set environment.SENDGRID_APIKEY=myKey \
      --set environment.DEFAULT_FROM_ADDRESS="my@email.com" \
      --set environment.DEFAULT_FROM_NAME="Lucas Santos"


# required function: This function in Helm ensures that a required value is provided in the Helm values file (values.yaml). If the specified value is missing or empty, Helm will throw an error with a message.
# $_ :=: This assigns the result of the required function to a throwaway variable ($_), which means the value is not actually used but is still validated
# .Values.environment & .Values.image.tag: These are placeholders for values that should be defined in the values.yaml file
{{- $_ := required ".Values.environment" .Values.environment }}
{{- $_ := required ".Values.image.tag" .Values.image.tag }}

# This approach enforces that essential values (environment and image.tag) are always defined in the values.yaml file before deploying a Helm chart. It helps prevent misconfigurations
