# in Blue-Green Deployment, we create both environments, then switch from Blue to Green (suddenly)
# each deployment has it's own service (2 deployments, 2 services, the service chooses the pod based on version)
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: v1 ####
  type: ClusterIP
  ports:
   - port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue ####
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    matchLabels:
      type: front-end
  replicas: 5
  template:
    metadata:
      labels:
        version: v1 ####
    spec:
      containers:
      - name: app-container
        image: my-app-image:1.0 ####


---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: v2 ####
  type: ClusterIP
  ports:
    - port: 80
     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green ####
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    matchLabels:
      type: front-end
  replicas: 5
  template:
    metadata:
      labels:
        version: v2 ####
    spec:
      containers:
      - name: app-container
        image: my-app-image:2.0 ####
        
