---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
automountServiceAccountToken: false  # each ServiceAccount has a token


# deployment with custom ServiceAccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      name: web-dashboard
  template:
    metadata:
      labels:
        name: web-dashboard
    spec:
      serviceAccountName: dashbaord-sa  ### add the custom serviceAccount in spec.template.spec.serviceAccountName
      containers:
        - image: gcr.io/kodekloud/customimage/my-kubernetes-dashboard
          name: web-dashboard


# create a pod with specific service account
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  serviceAccountName: myuser # we use pod.spec.serviceAccountName
  containers:
    - name: nginx
      image: nginx
