---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
automountServiceAccountToken: false  # each ServiceAccount has a token


# deployment with custom ServiceAccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      name: web-dashboard
  template:
    metadata:
      labels:
        name: web-dashboard
    spec:
      serviceAccountName: dashbaord-sa  ### add the custom serviceAccount in spec.template.spec.serviceAccountName
      containers:
        - image: gcr.io/kodekloud/customimage/my-kubernetes-dashboard
          name: web-dashboard


# create a pod with specific service account
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  serviceAccountName: myuser # we use pod.spec.serviceAccountName
  containers:
    - name: nginx
      image: nginx

# we have serviceAccount called neptune-sa-v2 in neptune namespace, get the token for this serviceaccount
# the token comes from the secret that belong to the serviceAccount
k -n neptune get sa
K -n neptune get secrets
k -n neptune get secret neptune-secret-1 -o yaml

cat "VALUE-FROM-SECRET-FILE" | base64 -d > /opt/course/5/token

