# daemonset
# used when you want to run one pod on each node, such as monitoring tools for example fluentD or proxy suchs calico or prometheus-exporters
# daemonset will create an many pods as there are nodes in cluster
# we don't set number of replicas on daemonset as it automatically deploys a pod on each node
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: fluentd
          image: fluentd:v2.5.2
          resources:
            limits:
              memory: 256Mi
              cpu: "0.25"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: varlog
          # daemoonset volumes use hostPath since the always run on specific node
          hostPath:
            path: /var/log

            
# Create a DaemonSet named configurator , it should: be in Namespace configurator , use image bash , mount /configurator as HostPath volume on the Node it's running on, write "aba997ac-1c89-4d64" into file /configurator/config on its Node 
# via the "command:" section, be kept running using "sleep 1d" or similar after the file write command
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: configurator
  namespace: configurator
  labels:
    k8s-app: conf
spec:
  selector:
    matchLabels:
      k8s-app: conf
  template:
    metadata:
      labels:
        k8s-app: conf
    spec:
      volumes:
      - name: my-vol
        hostPath:
          path: /configurator
      containers:
      - name: configurator
        image: bash
        command: ["/bin/sh"]
        args: ["-c", "echo 'aba997ac-1c89-4d64' > /configurator/config; sleep 1d;"]
        volumeMounts:
        - name: my-vol
          mountPath: /configurator
          
# Ensure a single instance of pod nginx is running on each node of the Kubernetes cluster where nginx also represents the Image name which has to be used. 
# Do not override any taints currently in place. 
# => Use DaemonSet to complete this task and use ds-kusc00201 as DaemonSet name.
# Do not override any taints => do not edit Node taints, change pod tolerations to be able to deploy pods on controlplane node
    # k get nodes --show-labels
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-kusc00201
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # these ones allow the pod to even run on controlplane
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: nginx
        image: nginx

# use namespace "project-1" for following. create DaemonSet named "daemon-imp" with image "httpd:2.4-alpine" and labels "id=daemon-imp" and "uuid=184". 
# its pods should request "20 millicore" cpu and "20 mebabytes" memory. the pods of the daemonset should run on ALL Nodes, including controlplanes
k get nodes --show-labels
k get ns
k create ns project-1 # in case not existing

apiVersion: v1
kind: DaemonSet
metadata:
  name: daemon-imp
  namespace: project-1
  labels:
    id: daemon-imp
    uuid: 18426a0b-5f59-4e10-923f-c0e078e82462
spec:
  selector:
    matchLabels:
    id: daemon-imp
    uuid: 18426a0b-5f59-4e10-923f-c0e078e82462    
  template:
    metadata:
      labels:
        id: daemon-imp
        uuid: 18426a0b-5f59-4e10-923f-c0e078e82462    
    spec:
      tolerations:
      # It was requested that the DaemonSet runs on all nodes, so we need to specify the toleration for this
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - image: httpd:2.4-alpine
        name: daemon-imp
        resources:
          requests:
            memory: 20Mi
            cpu: 20m

k get ds -n project-1 -o wide
k get po -n project-1 -o wide # check the nodes where pods are running on
