# daemonset
# used when you want to run one pod on each node, such as monitoring tools for example fluentD or proxy suchs calico or prometheus-exporters
# daemonset will create an many pods as there are nodes in cluster
# we don't set number of replicas on daemonset as it automatically deploys a pod on each node
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: fluentd
          image: fluentd:v2.5.2
          resources:
            limits:
              memory: 256Mi
              cpu: "0.25"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: varlog
          # daemoonset volumes use hostPath since the always run on specific node
          hostPath:
            path: /var/log

            
# Create a DaemonSet named configurator , it should: be in Namespace configurator , use image bash , mount /configurator as HostPath volume on the Node it's running on, write "aba997ac-1c89-4d64" into file /configurator/config on its Node 
# via the "command:" section, be kept running using "sleep 1d" or similar after the file write command
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: configurator
  namespace: configurator
  labels:
    k8s-app: conf
spec:
  selector:
    matchLabels:
      k8s-app: conf
  template:
    metadata:
      labels:
        k8s-app: conf
    spec:
      volumes:
      - name: my-vol
        hostPath:
          path: /configurator
      containers:
      - name: configurator
        image: bash
        command: ["/bin/sh"]
        args: ["-c", "echo 'aba997ac-1c89-4d64' > /configurator/config; sleep 1d;"]
        volumeMounts:
        - name: my-vol
          mountPath: /configurator
          
