# create a snapshot of the existing etcd instance running at https://127.0.0.1:2379, saving the snapshot to /var/lib/backup/etcd-snapshot.db
# ca certificate => /opt/kuin/ca.crt   client-certificate => /opt/kuin/etcd-client.crt  client-key => /opt/kuin/etcd-client.key
ssh controlplane
k get po -n kube-system # make sure there is a pod related to etcd here, it means that it is on this node
sudo -s  # backup can only be performed when you are root user
cat /etc/kubernetes/manifests/etcd.yaml  # find the folder with etcd certificates
ls -la /etc/kubernetes/pki/etcd
# --endpoints 127.0.0.1:2379  => since we are on same node this is NOT required here
ETCDCTL_API=3 etcdctl snapshot save /var/lib/backup/etcd-snapshot.db --endpoints 127.0.0.1:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key 
ls /var/lib/backup/etcd-snapshot.db  # file should be visible

# this is NOT reccomended. might damage the backup file!
# verify the snapshot
ETCDCTL_API=3 etcdctl --write-out=table snapshot status /var/lib/backup/etcd-snapshot.db


# restore an existing, previous snapshot located at /var/lib/backup/etcd-snapshot-previous.db => does NOT tell you where to backup!
# make sure that etcd user owns it otherwise you need to become a root user and change owner permission then you need to restore db backup
ls -la /var/lib/backup/etcd-snapshot-previous.db
# ussually etcd data files are saved at /var/lib/ folder
ETCDCTL_API=3 etcdctl snapshot restore /var/lib/backup/etcd-snapshot-previous.db --data-dir=/var/lib/new-etcd/ 
ls /var/lib/new-etcd/ # make sure it exists

# we need to change the hostPath for the etcd-data volume on etcd pod's yaml file to the restored database address:
vi /etc/kubernetes/manifests/etcd.yaml
    volumes:
    - hostPath:
          path: /var/lib/new-etcd/
          type: DirectoryOrCreate
      name: etcd-data
# takes around 3 minutes to re-start the etcd pod, during this time the kubectl can't be accessed!

k get po -n kube-system
    
# take the backup of the ETCD at the location "/opt/etcd-backup.db" on the "controlplane" node
export ETCDCTL_API=3
etcdctl snapshot save /opt/etcd-backup.db --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key --endpoint=127.0.0.1:2379 
