Pods
Pod commands and argos
Environment variables, value from cm and secret
Multi-Container PODs
Replicas and replicasets
Labels and Selectors 
Deployment
Deployment rollout and version
Deployment Strategy Rolling updates, Rollback
ConfigMaps
Secrets
Namespace
Namespace – Resource Limits 
Resource Quotas
Service svc
Docker and Containerd
Daemonsetds
Taints and Tolerations
Nodeselector
Nodeaffinity
Network policies ,ingress/egress
Ingress , Ingress Controller
Logging and monitoring, metrics server
Volumes, volumemount, pv, pvc, storage classes
Service Account

