# a container within the poller pod is hard-coded to connect to nginxsvc service on port 90, as this port changes to 5050
# an additional container needs to be added to the poller pod which adapts the container to connect to this new port, via ambassador container design

# update the nginxsvc service to serve on port 5050

# add an HAproxy container named haproxy bound to port 90 to the poller pod and deploy the enhanced pod.
# use the image haproxy and inject the configuration located at /opt/KDMC3323423/haproxy.cfg via a configmap
# named haproxy-config monuted to the container at /usr/local/etc/haproxy/haproxy.cfg

# update the original pod to connect to localhost instead of nginxsvc

# cat /opt/KDMC3323423/haproxy.cfg
# k create cm haproxy-config --from-file=/opt/KDMC3323423/haproxy.cfg
# k get cm cm haproxy-config

# another way to do it
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
        log stdout  format raw  local0

    defaults
        log     global
        mode    tcp
        timeout connect 10s
        timeout client  1m
        timeout server  1m

    frontend http-in
        bind *:90
        default_backend servers

    backend servers
        server server1 nginxsvc:5050 maxconn 32

# edit the service
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod1
  name: poller
spec:
  containers:
  - name: poller-container
    image: poller:stable
    env:
      - name: NGINX_HOST
        value: "localhost"
      - name: NGINX_PORT
        value: "90"
  - name: haproxy
    image: haproxy
    volumeMounts:
      - name: haproxy-config
        mountPath: /usr/local/etc/haproxy/haproxy.cfg
        subPath: haproxy.cfg
  volumes:
    - name: haproxy-config
      configMap:
        name: haproxy-config
