version: '6'
services: # services is a list of images with their detail       
  
  jupyter: # first image
    build:
      context: ./jupyter
    image: jupyter
    ports:  # ports for the image
      - "8888:8888"

      
  postgres: # second image
    image: postgres
    restart: always
    environment:  # username/password/databasename for the database image
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data
      POSTGRES_DB: data

      
    # link for the connection to the second image
    links:
      - postgres
    volumes:  # volumes for how to access files between host and container
          - "./notebooks:/notebooks" 
          - "./data:/data"
