kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer
  namespace: my-app
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "list", "create"]
  # only allowed on this specific resource inside this namespace
  resourceNames: ["myapp"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
  resourceNames: ["mydb"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jane-developer-binding
  namespace: my-app
# bind subject
subjects:
  - kind: User
    name: jane
    apiGroup: rbac.authorization.k8s.io
# to role
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
