apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-auto-scaler
  namespace: mddz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # can be also setup for any other microservice if needed
    name: config-server
  # controls how cautiously the HPA reduces (scales down) the number of pods.
  # HPA will wait 180 seconds (3 minutes) before scaling down, even if the metrics (CPU, memory, custom metrics) show that fewer pods are needed
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
  # Min-Max
  minReplicas: 1
  maxReplicas: 4
  metrics:
    # if cpu utilization reaches 70% , scale the pods up until it reaches 4 pods
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
